CREATE DATABASE IF NOT EXISTS AUpetsDB;
USE AUpetsDB;

CREATE TABLE IF NOT EXISTS Cliente (
    clienteId INT AUTO_INCREMENT PRIMARY KEY,
    clienteNome VARCHAR(126) NOT NULL,
    clienteCPF VARCHAR(11) NOT NULL UNIQUE,
    clienteEmail VARCHAR(254) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Pets (
    petId INT AUTO_INCREMENT PRIMARY KEY,
    petNome VARCHAR(50) NOT NULL,
    petRaca VARCHAR(50) NOT NULL,
    petIdade INT NOT NULL,
    clienteId INT NOT NULL,
    FOREIGN KEY (clienteId) REFERENCES Cliente(clienteId) ON DELETE CASCADE
);
